### PR TITLE
add exports to packages with multiple entry points

### LINKED ISSUE #87: Error with ESM
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import @vocab/core/runtime
```

Newer versions of node, when using esm, do not support importing a directory directly, without declaring the import explicitly in the exports field of the package.json. In Vanilla-extract the exports are explicitly defined like here: https://github.com/seek-oss/vanilla-extract/blob/master/packages/recipes/package.json. Maybe doing the same here for vocab will fix the issue. 

Another option would to move runtime, icu-handler and translation-file into their own packages and keep the packages flat.

### PR DESCRIPTION
**Pull request by mikebarkmin**
Fixes #87 and makes vocab more inline with Vanilla-Extract.

### CODE REVIEW

**Comment by askoufis** [comment]
Hi 👋 
Thanks for this PR!

The way vanilla-extract defines `exports` isn't ideal for [compatibility with bundlers _and_ node](https://webpack.js.org/guides/package-exports/#reference-syntax), so I'd prefer using `import` and `require` instead. Unfortunately, even this isn't perfect as vocab uses preconstruct for building which doesn't support outputting `.cjs` and `.mjs` file, though we're working on a solution for this that should be ready quite soon, so for now this will do.

**Comment by mikebarkmin** [comment]
Thank you for your explanation. I also think that the workaround should be merged for now, but of course a proper solution is much appreciated. I appreciate your affords.

**Comment by askoufis** [comment]
Sorry for the delay. Happy to approve, though I'm not sure what the lockfile changes are for. Would probably be best to remove them.

**Comment by mikebarkmin** [comment]
If have removed them.

**Review by askoufis — APPROVED** [review]

**Pull request merged**
